### PR TITLE
Merge fixes from master repository to ET4000PLUS-K7-rev-B

### PR DESCRIPTION
**Pull request by Vexisu**
## Changes in this version:
 - #17
 - #18
 - #23

### CODE REVIEW

**Comment by ArthurkaOriginal** [comment]
Hello, I compiled your firmware with OLED enabled, I encountered a problem: the printer does not see the SD card and does not print from it, printing is only possible by connecting to a computer and sending a print job through a slice. It is possible to install firmware, but printing is not possible. I hope for your help..
IMG-20241006-WA0000

**Comment by ArthurkaOriginal** [comment]
The print start button does not work

**Comment by Vexisu** [comment]
Hi. Did you tried to verify if the firmware build from the repo, without using a display, works correctly?

**Comment by ArthurkaOriginal** [comment]
I just checked, the firmware you compiled She sees the SD card and starts
printing.

I don't understand what the problem is, I only changed one value to make
the display work..

Can I ask you to compile the firmware with activated OLED tinyboy2? Please,
I think the problem is in my clumsiness, I did this for the first time and
I encounter failures

вс, 6 окт. 2024 г., 20:06 Maciej Waleryn ***@***.***>:

**Comment by ArthurkaOriginal** [comment]
I think there are no changes in the open source code that are in the finished firmware file. When I install the firmware compiled by you, everything works, when I compile it myself, it does not see the SD card and she won't let the file print

**Comment by Vexisu** [comment]
Okay, check if you're on the correct branch (ET4000PLUS-K7-rev-B) and the target in PlatformIO is set to mks_robin_lite_maple.

**Comment by ArthurkaOriginal** [comment]
I target in PlatformIO is set to mks_robin_lite , not maple. When I try to
compile mks_robin_lite_maple I always get an error (missing build script)

вс, 6 окт. 2024 г., 21:09 Maciej Waleryn ***@***.***>:

**Comment by Vexisu** [comment]
Could you send the error you get?

**Comment by ArthurkaOriginal** [comment]
I managed to do it, the problem was in the . platformio folder, I had to
delete it and go into the visual studio code several times...

I sincerely apologize for the inconvenience and the time you wasted. Thank
you very much for not leaving me without attention.

вс, 6 окт. 2024 г., 21:19 Maciej Waleryn ***@***.***>:

**Comment by Vexisu** [comment]
No problem. Glad it works now 😄

**Pull request merged**
